services:
  app:
    build:
      context: ./micro-pet-management
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SECURITY_USER: ${SECURITY_USER}
      SECURITY_PASSWORD: ${SECURITY_PASSWORD}
    restart: always
